export const UPDATE_NEW_MESSAGE_TEXT_SUCCESS =
  "UPDATE_NEW_MESSAGE_TEXT_SUCCESS";
export const UPDATE_NEW_MESSAGE_TEXT_PROCESSING =
         "UPDATE_NEW_MESSAGE_TEXT_PROCESSING";
export const UPDATE_NEW_MESSAGE_TEXT_FAILED = "UPDATE_NEW_MESSAGE_TEXT_FAILED";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const ADD_POST = "ADD_POST";
export const UPDATE_NEW_POST_TEXT = "UPDATE_NEW_POST_TEXT";
export const FOLLOW = "FOLLOW";
export const UNFOLLOW = "UNFOLLOW";
export const SET_USERS = "SET_USERS";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const SET_TOTAL_COUNT = "SET_TOTAL_COUNT";
